[build]
  command = "npm start"  # Command to start your Node.js application
  functions = "functions" # Directory with Netlify Functions (if applicable)
  publish = "public"     # Directory containing static files (e.g., CSS)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
